# https://github.com/marketplace/actions/sync-and-merge-upstream-repository-with-your-current-repository
name: Sync Upstream

on:
  schedule:
    - cron: '0 0,12 * * 1,3,5,0'
  workflow_dispatch:

jobs:
  sync:
    name: Sync Upstream
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v2
        with:
          ref: main

      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.1.0.b
        with: 
          token: ${{ secrets.WORKFLOW_TOKEN }}
          upstream_repo: https://github.com/zedeus/nitter.git
          upstream_branch: guest_accounts
          downstream_branch: guest_accounts
